### ISSUE TITLE
Add example using MUnit with Maven builds

### ISSUE THREAD

**Issue by olafurpg** [scalameta/munit#107]
The documentation currently doesn't explain how to setup MUnit with Maven. Here is an example repo that sets up MUnit with Maven https://gitter.im/scalameta/munit?at=5e9b77505706b414e1daea88

**Comment by sideeffffect** [comment]
direct link: https://github.com/milanvdm/munit-playground/blob/master/pom.xml

**Comment by tgodzik** [comment]
Btw. @sideeffffect  I also added munit in the example Maven g8 template here: https://github.com/scalameta/maven-scala-seed.g8

If there is something missing maybe we could add it there? We already added that template to Metals and is discoverable via new-scala-scala-project command.

**Comment by sideeffffect** [comment]
What would be also useful is an example how to make it work with the `maven-surefire-plugin` of the 3.x series. I wasn't able to figure it out :(
