### ISSUE TITLE
Enable MiMa in CI

### ISSUE THREAD

**Issue by olafurpg** [scalameta/munit#116]
Now that there are some external projects have published integrations with MUnit (https://github.com/47degrees/docker-testkit-munit) we should probably enable MiMa in CI so that we don't release new versions with accidental breaking changes.

**Comment by julienrf** [comment]
By the way, in the [documentation](https://scalameta.org/munit/docs/getting-started.html#stability) we can read that “there is no stability guarantees”. Is there a list of issues that need to be addressed before the API is stable? Would you recommend companies to start using MUnit now, or is the API likely to change?

**Comment by olafurpg** [comment]
My personal goal has been to release a v1.0 before the end of this year and never break binary compatibility after that. I have several small breaking changes I’d like to make at the moment 

* replace Unit with something like Any in return type of fixture methods to support async before/after hooks. Alternatively add async overloads, which should be source compatible. 
* move Fixture trait out of Suite so that it can be implemented with a basic toplevel class 
* (maybe) remove the TestValue type parameter and hardcode Future[Any]
* (maybe) do some minor source compatible refactorings

**Comment by olafurpg** [comment]
MUnit 2.12 had around 3k unique IP downloads in July so there seem to be some people using it outside of Scalameta projects.

**Comment by olafurpg** [comment]
There's a new v1.0 milestone to track issues that are blocking the v1.0 release https://github.com/scalameta/munit/milestone/1
