### ISSUE TITLE
ScalaCheckSuite unexpected behavior

### ISSUE THREAD

**Issue by barambani** [scalameta/munit#118]
It seems that the ScalaCheckSuite tests are not generating different values during the `forAll` iterations for types that are not collections or Strings (like `Int`, `Double` or even `UUID`). Tests like the below
```scala
final class IntGeneratorsSuite extends ScalaCheckSuite {

  val ints: mutable.Set[Int] = mutable.Set.empty

  property("generating int") {
    forAll { i: Int =>
      ints.add(i)
      println(ints)
      true
    }
  }

  test("generated int are not all the same") {
    assert(ints.size > 1)
  }
}
```
fail with the current master.  and print like
```
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
HashSet(-66888203)
[...]
```
This might be related to the fact that an initial seed is always set [here](https://github.com/scalameta/munit/blob/master/munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala#L56) and scalacheck copies that into the `Gen`'s initial seed and keeps using it to create values (see `genPrms` [here](https://github.com/typelevel/scalacheck/blob/f64f0cc3f21d9ba34848853181eaca1ebd60e39e/src/main/scala/org/scalacheck/Test.scala#L410) ,`forAllShrink` [here](https://github.com/typelevel/scalacheck/blob/09a243146f70a6f0b3ac02bde6013cd25675a314/src/main/scala/org/scalacheck/Prop.scala#L760) and `startSeed` [here](https://github.com/typelevel/scalacheck/blob/09a243146f70a6f0b3ac02bde6013cd25675a314/src/main/scala/org/scalacheck/Prop.scala#L517).
I'm not sure about what a possible solution could be. I played a bit with the code but I couldn't find any way to set an initial seed in the `Test`'s params and get different values as I was expecting.

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce. @gabro any idea what might be causing this?

**Comment by olafurpg** [comment]
The following diff makes the tests produce random values
```diff
-     val result = check(scalaCheckTestParameters, prop.useSeed(test.name, seed))
+     val result = check(scalaCheckTestParameters, prop)
```

**Comment by gabro** [comment]
oh wow, that's a big oversight on my part, thanks for reporting @barambani!

It seems I've misunderstood how seeding works in ScalaCheck so we're indeed generating a fixed seed for Gens.

I'll play around with it and see how we can fix it

**Comment by barambani** [comment]
Thank you for giving me/us this little jewel.
@olafurpg that change works, but then you are not able to get the seed for the report in case of failure. Also, even without that, the same issue appears if you set the initial seed in
```scala
override val scalaCheckTestParameters =
  super.scalaCheckTestParameters
    .withInitialSeed(1234L)
```
@gabro thanks a lot. It seems that the purpose of the initial seed set in scalacheck is to make the test reproducible. I tried to ping their channel ([here](https://gitter.im/scalacheck/Lobby?at=5eaabf1131a6d25d7c9dde1f)) to get a better idea of the possibilities. I will update if I get anything. Thanks again.
