### ISSUE TITLE
fatal errors thrown in scalacheck mode lose stacks

### ISSUE THREAD

**Issue by johnynek** [scalameta/munit#128]
see this discussion:

https://gitter.im/scalameta/munit?at=5eb9dc2310d5ec031aff33d9

you can repro it with a simple property:
```scala
  property("hide my stacks") {
    Prop.forAll { i: Int =>
      if (i > 0) throw new StackOverflowError()
      else Prop(true)
    }
  }
```

**Comment by olafurpg** [comment]
Thank you for reporting! There's a pending fix in #129

**Comment by olafurpg** [comment]
Fix released as 0.7.7

**Comment by johnynek** [comment]
Thank you so much! I appreciate your work on this. It is improving my enjoyment of using scala.

**Comment by olafurpg** [comment]
I’m glad to hear that! I didn’t anticipate so many people would be interested in MUnit, I started the project originally as an experiment to implement an sbt testing framework that reproduces the semantics of the Pants JUnit runner 😅

**Comment by johnynek** [comment]
I think many folks think scalatest is over complex. "Tests as values" also has a lot of customers. Lastly, your API is just very enjoyable, and the UX touches are really great in reporting.
