### ISSUE TITLE
discussion on assertEquals

### ISSUE THREAD

**Issue by gzoller** [scalameta/munit#151]
I know a while back the semantics of assertEquals changed... and broke 100s of my test cases. :-)

What was the reason for this change?

If I do:
```scala
val a = "foo"
val b = "foo"
a == b  // true
a.equals(b) // true
```
For all purposes a equals b, so why does assertEquals(a,b) return false?  Now I need to do: assert(a==b), which works, but I'm not clear.

**Comment by olafurpg** [comment]
Thank you for reporting! I'm unable to reproduce, the following test passes successfully when I run it
```
  test("i") {
    val foo = "foo"
    val bar = "foo"
    assertEquals(foo, bar)
  }
```

**Comment by olafurpg** [comment]
`assertEquals()` is implemented with `if (a != b) throwError()` so it's based on `==` equality. Can you elaborate on what is your expected behavior?

**Comment by gzoller** [comment]
Apologies!  I re-checked this and discovered a missing newline on a multi-line string I was comparing.  The test failed correctly.  When I added the newline, assertEquals worked just fine.
