### ISSUE TITLE
Add Scalafix rule for reporting .only in CI

### ISSUE THREAD

**Issue by gabro** [scalameta/munit#169]
Just an idea, see https://github.com/scalameta/metals/pull/1946#discussion_r460201294 for context, but in general `.only` annotations are useful for local development but should not be committed.

However it's easy to forget to remove them, so a Scalafix linting rule could help and could maybe be shipped with MUnit itself?

**Comment by olafurpg** [comment]
This is a nice idea.  I'd be open to merge a PR similar to https://github.com/scalameta/munit/pull/191 adding this rule. I'm gonna close this issue as wontfix given the limited activity.
