### ISSUE TITLE
Release Scala.js artifacts for Dotty builds

### ISSUE THREAD

**Issue by mpilquist** [scalameta/munit#199]
As of Dotty 0.27.0-RC1, we can start releasing Dotty Scala.js artifacts.

**Comment by olafurpg** [comment]
Thank you for reporting! I took a stab at implementing this here https://github.com/scalameta/munit/compare/master...olafurpg:dotty-js?expand=1 but I'm getting the error below

```
==> X munit.LinesSuite.basic 0.02s scala.scalajs.js.JavaScriptException: ReferenceError: JSPath is not defined
    at java.io.File$.separator(/Users/lgeirsson/dev/munit/tests/js/target/scala-0.27/tests-test-fastopt.js:733)
    at munit.Location.filename(/Users/lgeirsson/dev/munit/tests/js/target/scala-0.27/tests-test-fastopt.js:27493)
    at <jscode>.test__Lmunit_TestOptions__F0__Lmunit_Location__V.$c_sjsr_AnonFunction0(/Users/lgeirsson/dev/munit/tests/js/target/scala-0.27/tests-test-fastopt.js:53726)
    at scala.scalajs.runtime.AnonFunction0.apply(/Users/lgeirsson/dev/munit/tests/js/target/scala-0.27/tests-test-fastopt.js:32951)
```

If there was a way to make this method here return `false` then I think the problem would be fixed

https://github.com/scalameta/munit/blob/0c4ff57f667970e6574a4c7e02a6296e9feb8990/munit/js/src/main/scala/munit/internal/JSIO.scala#L88

Any help in this area would be greatly appreciated! cc/ @sjrd

**Comment by sjrd** [comment]
The error you are experiencing is a bug in the Scala.js support in dotty, which will be fixed in https://github.com/lampepfl/dotty/pull/9767. You'll probably have to wait for the next release.

Independently, your `def isNode` implementation looks buggy in Scala.js 1.x, whether for Scala 2 or 3. You should use `js.typeOf` instead:
```scala
js.typeOf(process) != "undefined" && js.typeOf(process.cwd) != "undefined"
```
The `js.isUndefined(process)` will throw a `ReferenceError` if `process` is not defined. (In 0.6.x it would have returned `undefined`, but not in 1.x.)

**Comment by olafurpg** [comment]
Thank you @sjrd ! I will wait until the next release then.

**Comment by smarter** [comment]
> I will wait until the next release then.

3.0.0-M1 has been released with the fix for the aforementioned bug. (Note that there's one known bug in the Scala.js support of M1 you may or may not run into with a workaround documented at: https://github.com/lampepfl/dotty/issues/10177).

**Comment by larsrh** [comment]
#248 adds DottyJS support
