### ISSUE TITLE
Test on last line of a file missing failure message 

### ISSUE THREAD

**Issue by benhutchison** [scalameta/munit#211]
I've observed that when a munit test defined on the _last line_ of a test file fails, the failure message is missing all the details. (Using Dotty 0.27). If the tests are re-ordered, the message is displayed normally.

Using debugger I narrowed down what's happening. This [line](https://github.com/scalameta/munit/blob/master/munit/shared/src/main/scala/munit/internal/console/Lines.scala#L28) expects slice array to have length 3, In my case, it has length 2.

So it drops through to the end of method and returns empty String as fail message. That in turn is because if `location.line` is the last line in lines, then taking a slice to `location.line + 1` wont add another line to the slice [here](https://github.com/scalameta/munit/blob/master/munit/shared/src/main/scala/munit/internal/console/Lines.scala#L26)

Perhaps this shows up more with dotty's optional braces where the test is on the last line of the file?

**Comment by benhutchison** [comment]
Workaround: add a comment to line after the last test

**Comment by SethTisue** [comment]
whoa, nice catch

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce. I opened https://github.com/scalameta/munit/pull/226 with a fix for this bug.
