### ISSUE TITLE
Release for Scala 3.0.0-M1

### ISSUE THREAD

**Issue by larsrh** [scalameta/munit#240]
ScalaCheck 1.15.0 has just been deployed to Sonatype, which should allow munit to be released.

**Comment by tgodzik** [comment]
I will take a look at making a PR if no one objects.

**Comment by larsrh** [comment]
A backported release of 0.7.15 would be great, too ☺

**Comment by tgodzik** [comment]
Thaaat might be harder as I have no idea how to release it locally :sweat_smile:

**Comment by olafurpg** [comment]
No need to back port, we can continue publishing new 0.7.x versions.

**Comment by larsrh** [comment]
True, there's no need, but it's a lot more convenient for downstream dependencies. It avoids churn going forward with 3.0.0-M*.

**Comment by tgodzik** [comment]
0.7.16 with support for `0.27.0-RC1` and `3.0.0-M1` is now released.
