### ISSUE TITLE
Avoid relying on Node's fs when running in browser-based JSEnv 

### ISSUE THREAD

**Issue by keynmol** [scalameta/munit#247]
## Problem

MUnit relies on Node.js' `fs` module to read the source location when an assertion fails.

This is only possible if SJS if told to emit `CommonJSModule` or `ESModule`:

```scala
 scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule)),
```

**Issue** is that one cannot use such modules in browser-based JSEnv, filesystem doesn't exist there. And tests fail with an exception:

```scala
[error] munit.internal.JSFs$ needs to be imported from module 'fs' but module support is disabled
[error]   called from private java.nio.file.Files$.$anonfun$readAllBytes$1(java.nio.file.Path)[byte
[error]   called from java.nio.file.Files$.readAllBytes(java.nio.file.Path)[byte
[error]   called from java.nio.file.Files$.readAllLines(java.nio.file.Path)java.util.List
[error]   called from private munit.internal.console.Lines.$anonfun$formatLine$1(java.nio.file.Path)[java.lang.String
[error]   called from munit.internal.console.Lines.formatLine(munit.Location,java.lang.String,munit.Clues)java.lang.String
[error]   called from munit.internal.console.Lines.formatLine(munit.Location,java.lang.String)java.lang.String
```

## Proposed solution

@sjrd and @olafurpg propose a fallback solution, akin to

```scala
try { js.Dynamic.global.require("fs") } catch { ... }
```

to avoid having `fs` a hard dependency for MUnit.

### Reference material

* Gitter thread: https://gitter.im/scala-js/scala-js?at=5fa6f6c52a60f731f73fa8f1
* Same issue solved differently in Weaver Test: https://github.com/disneystreaming/weaver-test/pull/82/files

**Comment by raquo** [comment]
@olafurpg Are you planning to solve this? If I understanding correctly, there is no workaround for testing projects that need JS DOM, right? Seems that the usefulness of Scala.js support is pretty limited if that's the case...

I was hoping to switch from ScalaTest to MUnit, but I have a lot of frontend tests that need `(Test / requireJsDomEnv) := true`.

**Comment by olafurpg** [comment]
No objections from me if somebody wants to implement the proposed fix. The fs module is optional, it’s only used to enrich error messages. We can merge the fix even with no tests to unblock this usecase.

**Comment by olafurpg** [comment]
What are the steps to reproduce this error? I tried to reproduce in the MUnit repo with the diff here but the tests run without errors https://github.com/scalameta/munit/compare/main...olafurpg:js-node-fs?expand=1

**Comment by olafurpg** [comment]
nvm, I was able to reproduce by removing the linker config settings.

**Comment by olafurpg** [comment]
I opened https://github.com/scalameta/munit/pull/376 replacing the usage of JS imports with `js.Dynamic.global.require("fs")`. @raquo @keynmol could you please try out the PR to validate that it fixes this issue?

**Comment by armanbilge** [comment]
I'm working on cross-building https://github.com/http4s/http4s/pull/4938 to Scala.js and ran into this issue too when trying to run the test suite on Firefox instead of Node.js. Very very glad to see a fix in the works.
