### ISSUE TITLE
3.0.0-M2 release

### ISSUE THREAD

**Issue by mpilquist** [scalameta/munit#263]
Scalacheck was just published so munit should be ready.

**Comment by djspiewak** [comment]
Once munit is done, most of the rest of the ecosystem can follow.

**Comment by SethTisue** [comment]
ScalaCheck has not published yet, afaict: https://github.com/typelevel/scalacheck/issues/723

and https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3.0.0-M2/1.15.1/ is 404 at present

**Comment by djspiewak** [comment]
It's done. Should be up within a few minutes

**Comment by olafurpg** [comment]
I opened https://github.com/scalameta/munit/pull/264 but there appear to be some breaking changes. I'm not familiar enough with the Scala 3 macro APIs to fix this myself.

**Comment by gabro** [comment]
Working on it in #265

**Comment by gabro** [comment]
Since we're at it, what do you all think about dropping 0.27.0-RC1?

I remember @djspiewak had opinions on support of previous versions

**Comment by olafurpg** [comment]
If it’s easy to support older versions then I think it’s worth keeping support for older versions to make the upgrade experience easier for downstream users.

**Comment by gabro** [comment]
Makes sense. We can probably drop most of scala 3/dotty older versions once Scala 3 stable is out.

I'll cut a new release soon

**Comment by gabro** [comment]
v0.7.19 on its way to Maven Central

**Comment by djspiewak** [comment]
For the record, I'm completely okay with dropping 0.27. :-) Keep M1 though, please. My policy is to maintain the latest two Scala 3 versions as cross targets if at all possible. My only exception to this is if things become untenably problematic to maintain the earlier target, in which case I cut it.

**Comment by gabro** [comment]
Thanks @djspiewak, for this specific instance we opted for keeping 0.27 since it was easy enough.

I think we'll eventually drop all non-stable Scala 3 versions once Scala 3.0.0 is out.

**Comment by djspiewak** [comment]
Yeah once 3 goes final, all the unstable versions should be dropped.
