### ISSUE TITLE
Release for Scala 3.0.0-RC1, please?

### ISSUE THREAD

**Issue by SethTisue** [scalameta/munit#311]

**Comment by tgodzik** [comment]
https://github.com/typelevel/scalacheck/pull/759 is merged so we should be soon able to release. Thanks for the reminder!

**Comment by larsrh** [comment]
There's currently a problem:

```
[error] (jvm / doc / scalaInstance) Couldn't retrieve `org.scala-lang:scala3doc:3.0.0-RC1`.
[error] Total time: 33 s, completed Feb 16, 2021, 4:51:19 PM
sbt '+ jvm/publishSigned' failed: 1
```

Only nightlies are available here:

https://repo1.maven.org/maven2/org/scala-lang/scala3doc_3.0.0-RC1/

**Comment by gabro** [comment]
we can easily bypass `doc` for publishing, but it would be nicer to have all the dependencies lined up

**Comment by gabro** [comment]
@tgodzik I can take care of it if you didn't start already

**Comment by tgodzik** [comment]
I added a fix to make it compile in https://github.com/scalameta/munit/pull/312 but not sure about what you mean exactly about bypassing @gabro

**Comment by tgodzik** [comment]
@larsrh I think the name changed? There is https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3.0.0-RC1/3.0.0-RC1/

**Comment by gabro** [comment]
@tgodzik I just meant skipping the `doc` task on Scala 3 to move on with the publishin

**Comment by tgodzik** [comment]
@gabro We can do that for sure, but it seems to work with newest dotty plugin and sbt versions.

**Comment by larsrh** [comment]
> I think the name changed?

Maybe? But I think this requires an update in sbt-dotty. I don't think I can configure the name in the build.

**Comment by larsrh** [comment]
lampepfl/dotty#11416

**Comment by tgodzik** [comment]
> > I think the name changed?
> 
> Maybe? But I think this requires an update in sbt-dotty. I don't think I can configure the name in the build.

Actually it doesn't work with the newest, so you are right. Let me raise it somewhere.

**Comment by larsrh** [comment]
Scalacheck release started

**Comment by larsrh** [comment]
1.15.3 out

**Comment by SethTisue** [comment]
did it actually publish, or did this ticket just auto-close?

**Comment by tgodzik** [comment]
I can release a new version unless anyone else is working on it yet?

**Comment by tgodzik** [comment]
Running it here https://github.com/scalameta/munit/actions/runs/572912654

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/scalameta/munit_3.0.0-RC1/0.7.22/
