### ISSUE TITLE
Add a way to structure tests.

### ISSUE THREAD

**Issue by ohechtl** [scalameta/munit#323]
Hey, I've used Scalatest and recently started using MUnit, and I really like the beutiful error messages it provides. Although it'd be great to have a structurability function offered by `FunSuite`, like the one in ScalaTest called `describe`. 

What is the opinion of the devs about this? Is this planned or would unnecesarily complicate test suites?

**Comment by olafurpg** [comment]
Thank you for reporting! This looks related to https://github.com/scalameta/munit/issues/93 and https://github.com/scalameta/munit/pull/133

**Comment by ohechtl** [comment]
Thank you for your quick reply, I've found enough information and also a workaround for now, so I'm closing this ticket.
