### ISSUE TITLE
Cannot run test file in IDEA 2021.1

### ISSUE THREAD

**Issue by mr-git** [scalameta/munit#345]
When attempting to run unit-test file `TestSpec` like described in https://scalameta.org/munit/docs/getting-started.html#run-tests-in-intellij, IDEA shows red error message, like:
```
Error running 'TestSpec':
com/intellij/rt/junit/JUnitStarter
```
![image](https://user-images.githubusercontent.com/8796159/113975064-9ed82f00-9847-11eb-8ca2-370bca7a62aa.png)

When run from SBT with `test` or `testOnly *TestSpec*` - all works as expected.

Maybe latest IDEA changed something in unit-test starter?

**Comment by olafurpg** [comment]
Thank you for reporting! This looks like an IntelliJ regression since nothing changed on the MUnit side. Can you report to YouTrack instead?

**Comment by mr-git** [comment]
done: https://youtrack.jetbrains.com/issue/SCL-18912

**Comment by mr-git** [comment]
it was not obvious - `JUnit` plugin has to be enabled for this to work.

It might be good to amend the web-site to mention that plugin must be enabled.
To speed up loading of IDEA, I've disabled all non-required plugins, somehow `ScalaTest` tests were working just find without it, I guess support for them is embedded in `Scala` plugin
