### ISSUE TITLE
Inner async tests are not executed

### ISSUE THREAD

**Issue by IvannKurchenko** [scalameta/munit#349]
Hi, Thanks for a great product.

I've faced with next issue - when I have nested or inner test which has `Future` with assertion inside it always passing and sometimes even not executed.
Example:
```
class InnerAsyncTest extends munit.FunSuite {
    test("outer test") {
        test("inner test") {
             Future(assertEquals("actual", "expected"))  
         }   
     }
}
```

But simple removing of intermediate test fixes problem:

```
class InnerAsyncTest extends munit.FunSuite {
    test("single big test") {
        Future(assertEquals("actual", "expected"))     
     }
}
```

Munit version: `0.7.23`

**Comment by SethTisue** [comment]
why closed?

**Comment by IvannKurchenko** [comment]
@SethTisue  I think it is something that might be on my side, I'm sorry, I saw that regular nested tests do not work for me as well.
