### ISSUE TITLE
Publish for Scala 3.0.0-RC3

### ISSUE THREAD

**Issue by SethTisue** [scalameta/munit#350]
...which just hit Maven Central!

**Comment by gabro** [comment]
On it :)

**Comment by gabro** [comment]
MUnit 0.7.24 with Scala 3.0.0-RC3 support is on its way to Maven Central :shipit:

**Comment by gabro** [comment]
Woops, I mixed up `main` and `master` and botched the release. 0.7.25 on its way, 0.7.24 is broken
