### ISSUE TITLE
Implement interceptFilter

### ISSUE THREAD

**Issue by lambdista** [scalameta/munit#356]
Besides `intercept` and `interceptMessage` I think it could be useful having an `interceptFilter` method:
```
def interceptFilter[T <: Throwable](predicate: T => Boolean)(
    body: => Any
)
```
The test would pass if, given the exception `t: T` thrown by `body`, `predicate(t) == true`.
If interested I can implement it and open a PR. Of course I'm very open to discuss its name or anything else.

**Comment by olafurpg** [comment]
Thank you for reporting! Have you tried to use the return value of `intercept`?
```scala
val exception = intercept[FileNotFoundException](haha())
assertEquals(exception.getMessage, "/path/to/file")
```

**Comment by olafurpg** [comment]
One problem with `predicate: Throwable => Boolean` is that you can't produce a custom error message when the predicate fails. You can only fail with a generic message like "predicate failed", similar to `Future[T].withFilter()` or `Try[T].withFilter()`.

**Comment by lambdista** [comment]
You're right, indeed in order to implement `interceptFilter` I had to refactor `runIntercept`, used by both `intercept` and `interceptMessage` so that I could reuse it for `interceptFilter` too:
```
  private def runIntercept[T <: Throwable](
      predicate: T => Boolean,
      errBuilder: Throwable => String,
      body: => Any
  )
```
And this is the `errBuilder` for `interceptFilter`:
```
val errBuilder: Throwable => String = e =>
      s"intercept failed, exception '${e.getClass().getName()}' had message '${e.getMessage}', which doesn't satisfy the predicate"
```
That said I think you're right about using the return type of `intercept`. You know, having seen there's already `interceptMessage`, while it could have been emulated just like you wrote above, I thought a dedicated method for filtering could have been useful but I understand that `interceptMessage` could still make sense because of its detailed error message.
Thank you for your reply. I guess you can close this issue. Cheers!
