### ISSUE TITLE
Testing for non-compilation wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [scalameta/munit#36]
Should help a lot when working with macros or as examples of illegal usage cases instead of documenting them in comments like [here](https://github.com/pathikrit/dijon/pull/38/files#diff-0624b84e27a463a007fc3f6922ef83f8R280)

**Comment by olafurpg** [comment]
Thank you for reporting! Opened #58 adding a `compileErrors(String): String` macro that should unblock this use-case.

**Comment by olafurpg** [comment]
Docs https://scalameta.org/munit/docs/assertions.html#compileerrors

I have pushed a tag v0.5.2 to trigger a release
