### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by stefanobaghino** [scalameta/munit#365]
I would like to re-use (part) of the code under `munit/shared/src/main/scala/munit/internal/difflib` -- I looked around for licensing information about it but could not find anything. Would it be ok for me to re-use that code freely? If you can, adding a license could be useful. :slightly_smiling_face:

**Comment by gabro** [comment]
Hey @stefanobaghino, thanks for pointing that out. The project is licensed under the Apache 2.0 license, but the only place where this is referenced is https://github.com/scalameta/munit/blob/main/build.sbt#L27-L29 but it we would definitely need to add it to the repo as well.

**Comment by olafurpg** [comment]
Thank you for reporting! Please preserve the NOTICE from the original google-difflib. The MUnit implementation is a line-by-line rewrite in Scala

**Comment by stefanobaghino** [comment]
Ah-ah, thanks for the info!
