### ISSUE TITLE
Add failSuite() helper to abort the entire test suite

### ISSUE THREAD

**Issue by olafurpg** [scalameta/munit#37]
Currently, you can use `fail()` to abort a single test case with a custom message. However, the next test case will continue to run unchanged.

It would be nice if there was a `failSuite()` helper that would abort subsequent test cases as well.

Context: https://contributors.scala-lang.org/t/announcing-munit-a-new-scala-testing-library/4007/5?u=olafurpg

**Comment by olafurpg** [comment]
cc/ @daron666 will you look into this?

**Comment by daron666** [comment]
@olafurpg yep!
