### ISSUE TITLE
Add to Dotty community build

### ISSUE THREAD

**Issue by gabro** [scalameta/munit#38]
MUnit stresses a few Dotty features (and we actually hit on and reported a compiler bug when implementing Dotty support) so I think it would make sense to include it in https://github.com/lampepfl/dotty/tree/master/community-build/test/scala/dotty/communitybuild

**Comment by SethTisue** [comment]
you beat me to suggesting this :-)

**Comment by gabro** [comment]
https://github.com/lampepfl/dotty/pull/8236

**Comment by gabro** [comment]
Merged 🎉
