### ISSUE TITLE
munit.Location incompatible with Gradle build caching and Distributed Testing

### ISSUE THREAD

**Issue by DanielThomas** [scalameta/munit#382]
The compiler macro embeds the fully qualified path to the source file for location at test runtime, however this causes the output to not be portable between machines, making it incompatible with Gradle build caching (or anything that wants to ship test artifacts outside the immediate build environment for that matter).

This also means that tests can't be distributed using the distributed test mechanism, as all resources need to be available via the classloader:

https://docs.gradle.com/enterprise/test-distribution-gradle-plugin/#tests_reading_files_from_src_test_resources

Attempting to locate source files as relative classloader resources before falling back to the file system would provide the flexibility necessary to implement support for both of these features downstream, and allow tests to be packaged with their sources in a standalone jar for running outside of the build tool.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/scalameta/munit/pull/823
