### ISSUE TITLE
Ability to add parameters to `test("something")` for scenarios where values only available with injection

### ISSUE THREAD

**Issue by GavinRay97** [scalameta/munit#383]
Realworld scenario: Trying to test Vert.x + Scala apps.

Vert.x has their own testing integration called `Vert.x Unit` that's based on JUnit 4, as well as a JUnit 5 integration (but JUnit 5 doesn't seem well-supported in Scala-land right now so it seemed off the table):
- https://vertx.io/docs/vertx-unit/java/
- https://vertx.io/docs/vertx-junit5/java/

```scala
object Test:
  var vertxDeploymentId: String = ""

  @BeforeClass
  final def setup() =
    val maxWaitTime: FiniteDuration = Duration(5, TimeUnit.SECONDS)
    vertxDeploymentId = Await.result(VertxScala(Vertx.vertx).deployVerticle(new HttpVerticle()), maxWaitTime)

  @AfterClass
  final def teardown() =
    VertxScala(Vertx.vertx).undeploy(vertxDeploymentId)

@RunWith(classOf[VertxUnitRunner])
class Test:
  @Test def t1(testContext: TestContext) =
	// injected here
```

I have tried to mimic this with MUnit, but it doesn't appear to function at all:
```scala
abstract class FunSuite extends munit.FunSuite {
  def test(name: String)(body: (TestContext) => Any)(implicit loc: munit.Location): Unit = {
    test(new munit.TestOptions(name))(body)
  }
}

@RunWith(classOf[VertxUnitRunner])
class MUnitExample extends FunSuite {

  test("my test") { (testContext: TestContext) =>
    munit.Assertions.assert(testContest != null)
    println(f"MUnit testContext is: $testContext")
  }
}
```

Some solution to this would be great, even like:
```scala
test("my test", (testContext: TestContext) => {
  munit.Assertions.assert(testContext != null)
  println(f"MUnit testContext is: $testContext")
})
```

**Comment by gabro** [comment]
Hi, thanks for reporting! Have you taken a look at functional fixtures? https://scalameta.org/munit/docs/fixtures.html#functional-test-local-fixtures

They look like a great fit for your use case

**Comment by GavinRay97** [comment]
Thanks for responding so quickly -- I'd be happy to use those if they work with the parameter dependency injection.

I had looked at them and wasn't sure how I could emulate this:
```scala
 @Test def t1(testContext: TestContext) =
```

Since `testContext` is injected in a special way by the Vert.x runner into JUnit test arguments by some magic it does I think
