### ISSUE TITLE
Blocking Async Tests

### ISSUE THREAD

**Issue by Slakah** [scalameta/munit#40]
It looks like the current async runner requires blocking [`Await.result`](https://github.com/scalameta/munit/blob/ee3bff52619a3e93662f35a3ff7a821d9133e5f9/munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala#L10). This also has the adverse result that async code is not testable in JS, see: https://github.com/scalameta/munit/blob/ee3bff52619a3e93662f35a3ff7a821d9133e5f9/munit/js/src/main/scala/munit/internal/PlatformCompat.scala#L19 .

Utest works around this by providing an async interface with callbacks for the JS side, and on the JVM side will block on the full evaluation of the test tree.

**Comment by olafurpg** [comment]
Thanks for reporting! This should be fixed in https://github.com/scalameta/munit/pull/39

I didn't fully understand the purpose of the continuation callback in the Scala.js testing interface but now I understand it :)

**Comment by olafurpg** [comment]
Fixed in #39. I'll cut a new v0.5 release now
