### ISSUE TITLE
Add assertSameElements helper

### ISSUE THREAD

**Issue by poslegm** [scalameta/munit#45]
It may be reasonable to have `assertSameElements` function that ignores elements order on collection comparison.

Now user forced to write something like this `assert(diff("master").toSet == Set(f1, f2))`

**Comment by SethTisue** [comment]
(once you start adding this kind of thing it's very hard to know when to stop. or whether to start in the first place...)

**Comment by olafurpg** [comment]
Thank you for reporting! I'm on the fence about this helper function. I would recommend instead to use `assertEquals(a.sorted, b.sorted)` or `assertEquals(a.toSet, b.toSet)`, which is clearer to read IMO.

When comparing large data structures with a hardcoded "expected" value then I normally render the "obtained" value into a multiline string and use `assertNoDiff`. The benefit of this approach is that test failures are readable with the diffs and you can easily copy-paste the "obtained" output from the formatted error message.
