### ISSUE TITLE
compileErrors unusable when code passed in invokes scala.compiletime.error

### ISSUE THREAD

**Issue by Lasering** [scalameta/munit#453]
Example code, in Scala 3.1.0:

```scala
import scala.compiletime.{error, codeOf}
class MySuite extends munit.FunSuite {
  inline def testError(inline typeName: Any): String = error("Got error " + codeOf(typeName))
  
  test("hello") {
    val error = compileErrors("""testError("string")""")
    val expectedError = """Got error "string""""
    assertNoDiff(error, expectedError)
  }
}
```
[Scastie Link](https://scastie.scala-lang.org/Q8w8BTWET3a1O9A5rLuAIw)

This test suite fails to compile on line `val error = compileErrors("""testError("string")""")` with error `Got error "string"`

**Comment by olafurpg** [comment]
Thank you for reporting! There isn’t much MUnit can do about this since the compileErrors macro is using a standard helper from Scala 3 to compile string literals. You may get better help by reporting an issue to Scala 3
