### ISSUE TITLE
Tests duplication in IDEA console

### ISSUE THREAD

**Issue by poslegm** [scalameta/munit#47]
IDEA renders each test three times, but executes once.

Reproduces on [ScalafmtVersionSuite](https://github.com/poslegm/scalafmt/blob/munit/scalafmt-dynamic/src/test/scala/tests/ScalafmtVersionSuite.scala) with IDEA 2019.3.2 (Windows / MacOS)

![17db6c5bfb9c8496](https://user-images.githubusercontent.com/4687050/74089025-c39f0e00-4aad-11ea-8251-c007d1672653.png)

**Comment by olafurpg** [comment]
Thank you for reporting! I was able to reproduce and track down the issue. Will open a fix soon
