### ISSUE TITLE
No way to «go to test definition» in IDEA

### ISSUE THREAD

**Issue by poslegm** [scalameta/munit#48]
1. It would be helpful to go to test definition line in code when double clicking on the failed test name in console
2. There is no clickable source location for error (`at munit.Assertions.fail(Assertions.scala:134)` only)

![Screen_Shot_2020-02-07_at_7 33 38_PM](https://user-images.githubusercontent.com/4687050/74089098-94d56780-4aae-11ea-9380-cfb7185838d9.png)

**Comment by poslegm** [comment]
Intellij doesn't see separate tests at all.

Another JUnit integration features which MUnit don't have:

Right-Click dropdown
![Screen Shot 2020-03-22 at 12 27 02 AM](https://user-images.githubusercontent.com/4687050/77236997-0a1b7880-6bd5-11ea-9b73-e177db94c2a8.png)

Run separate test button
![Screen Shot 2020-03-22 at 12 27 11 AM](https://user-images.githubusercontent.com/4687050/77236999-0be53c00-6bd5-11ea-96c9-42d0bffdd715.png)

I suspect that it works with [ScalaTestFinder](https://github.com/JetBrains/intellij-scala/blob/278113b655c934d53a0d7da0ffae81124d0d723b/scala/scala-impl/src/org/jetbrains/plugins/scala/testingSupport/ScalaTestFinder.scala#L20-L43) for Scala frameworks and with [JUnitUtil](https://github.com/JetBrains/intellij-community/blob/master/java/execution/impl/src/com/intellij/execution/junit/JUnitUtil.java#L131-L155) for JUnit. For JUnit IDEA recognizes annotated methods only.

So, full IDEA support looks impossible without changes to intellij-scala plugin 😕

**Comment by poslegm** [comment]
There is one way to do it without modifying intellij sources: own plugin for IDEA.

We can look at ZIO: they have testing framework [zio-test](https://github.com/zio/zio/tree/master/test) and Intellij plugin with custom [test runner](https://github.com/zio/zio-intellij/blob/idea193.x/testrunner_2.13/src/main/scala/zio/intellij/testsupport/runner/ZTestRunner.scala)
![Screen Shot 2020-04-01 at 4 55 50 PM](https://user-images.githubusercontent.com/4687050/78145528-ac3f2a00-7439-11ea-9c5d-45ad24b9b405.png)

**Comment by olafurpg** [comment]
I would prefer to contribute the test runner to IntelliJ Scala plugin instead. I believe they would be open to merge the implementation if it's contributed. It may be harder to convince them to implement it for us 😏

**Comment by olafurpg** [comment]
I'm still waiting for the download numbers for March, but munit_2.12 had 7k unique IP downloads in February which is very high considering it's a new library.

**Comment by poslegm** [comment]
related: https://youtrack.jetbrains.com/issue/SCL-17360

**Comment by francisdb** [comment]
Looks like intellij now has munit support:
https://blog.jetbrains.com/scala/2020/12/01/intellij-scala-plugin-2020-3/#munit-support
(not sure if this fixes this issue)

**Comment by gabro** [comment]
Looks like! 

The issue linked by @poslegm is closed as well, so I suppose that's it.

Thanks @francisdb for letting us know, I'll go ahead and close this. We can reopen if I misunderstood the IJ's changelog
