### ISSUE TITLE
`flaky` tag doesn't work with `fail` one

### ISSUE THREAD

**Issue by danicheg** [scalameta/munit#482]
If a test passes and it was marked by the `flaky` and `fail` tags that cause the `expected failure but test passed` error. Is it expected behavior? I mean that tests where failure is expected also can be flaky in themselves. 
`MUnit` version is `0.7.29`.

**Comment by olafurpg** [comment]
Thank you for reporting! Can you provide a minimal reproduction? I tried to reproduce in the PR https://github.com/scalameta/munit/pull/484 but the test succeeds as expected 🤔

**Comment by danicheg** [comment]
I confirm, `MUnit` works as expected. It's another reminder that a tiny-clear reproduction is always needed to do :)
