### ISSUE TITLE
Don't swallow exceptions when they have no stack traces

### ISSUE THREAD

**Issue by jvican** [scalameta/munit#51]
I've just run into an issue where MUnit wouldn't report an exception thrown when it has no writable stack trace. Libraries such as jsoniter-scala might throw exceptions with no writable stack traces by default to avoid their performance penalty.

You can reproduce this issue with the following snippet.

```scala
class SwallowedExceptionSpec extends FunSuite {
  test("i am reported as success but i should be failure") {
    class SwallowedException(msg: String, withStackTrace: Boolean)
      extends RuntimeException(msg, null, false, withStackTrace)
    throw new SwallowedException("i am not reported", false)
  }
}
```
  
Changing the previous code to `throw new SwallowedException("i am not reported", true)` would make munit report the failed test case as expected.

I am using version 0.4.5 and Scala version 2.13.1.

**Comment by jvican** [comment]
Running the previous case with the JUnit runner makes it fail, so I suspect the issue is coming from MUnit runner.

**Comment by olafurpg** [comment]
Thanks for reporting! I'm able to reproduce. Looking into what's going on 🤔

**Comment by olafurpg** [comment]
The issue was caused by an uncaught exception in junit-interface processing the stack trace. I've cut a new release in https://github.com/olafurpg/junit-interface/runs/446331956

**Comment by olafurpg** [comment]
Pending fix https://github.com/scalameta/munit/pull/52

**Comment by olafurpg** [comment]
Pushed tag 0.4.6 including this fix
