### ISSUE TITLE
Support Scala Native for Scala 3

### ISSUE THREAD

**Issue by thesamet** [scalameta/munit#524]
Scala native now supports Scala 3.1.x. In conjunction with [sbt 1.7.0-M2](https://github.com/sbt/sbt/releases/tag/v1.7.0-M2) it is possible to use Scala 3.1 while still remaining backward compatible for Scala 3.0 users.

**Comment by mzuehlke** [comment]
In the meantime munit supports the latests Scala 3 LTS  and Scala Native versions.
This issue can be closed.
