### ISSUE TITLE
Non-termination regression with scala-cli starting with 1.0.0-M2

### ISSUE THREAD

**Issue by lbialy** [scalameta/munit#540]
Hi,

I have tried using latest munit versions with scala-cli and found out that termination does not occur if all tests pass since 1.0.0-M2 (M1 works just fine, as all the 0.7.x versions). I have a repro repo here:

https://github.com/lbialy/munit-nonterm-issue

Just run `scala-cli test .` in this directory and it should hang after printing that all tests passed.

My scala-cli version is 0.1.8.

**Comment by armanbilge** [comment]
Seems the issue was introduced in literally the first PR after 1.0.0-M1 :)

- https://github.com/scalameta/munit/pull/435

```scala
//> using lib "org.scalameta::munit::1.0.0-M1+1-11ee9d1c-SNAPSHOT"
//> using repository "https://oss.sonatype.org/content/repositories/snapshots/"
class SanityTest extends munit.FunSuite:
  test("sanity") {
    assert(2 + 2 == 4)
  }
```

**Comment by bishabosha** [comment]
I tested this again recently with scala-cli 0.1.17

**Comment by alexarchambault** [comment]
munit should create daemon threads around [here](https://github.com/scalameta/munit/blob/a16b465873aea769825162d9faa6e12d5fe78d7d/munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala#L15) to fix this, I think. See [how Scala CLI does](https://github.com/VirtusLab/scala-cli/blob/30504be3f9a70ad3f3cef62dd08f953d29f14175/modules/build/src/main/scala/scala/build/BuildThreads.scala#L20-L22) for example.

**Comment by SethTisue** [comment]
anybody here have any insight on https://github.com/VirtusLab/scala-cli/issues/2623 ?
