### ISSUE TITLE
Documentation Request: Change Notes

### ISSUE THREAD

**Issue by gzoller** [scalameta/munit#605]
I see munit has moved to 1.0.0 (M anyway).  That's a bump from the pre-1 versions.
What I don't see (at least easily) is any reference to what has changed or been added, ie a "New" section in the documentation.
That would be nice to have to understand what additions are coming in the latest version.

**Comment by valencik** [comment]
1.0.0 has been released!
There are release notes in the blog post:
https://scalameta.org/munit/blog/2024/05/22/release-1.0.0.html
