### ISSUE TITLE
Cannot get rich filtering capabilities example working

### ISSUE THREAD

**Issue by MrPowers** [scalameta/munit#62]
I am really excited about the [rich filtering capabilities](https://scalameta.org/munit/blog/2020/02/01/hello-world.html#rich-filtering-capabilities)!

Here's the example on the website that I cannot get working:

```scala
import scala.util.Properties
import munit._
object Windows213 extends Tag("Windows213")
class MySuite extends FunSuite {
  // reminder: type Test = GenericTest[Any]
  override def munitNewTest(test: Test): Test = {
    val isIgnored =
      options.tags(Windows213) && !(
        Properties.isWin &&
        Properties.versionNumberString.startsWith("2.13")
      )
    if (isIgnored) test.withBody(() => Ignore)
    else test
  }

  test("windows-213".tag(Windows213)) {
    // Only runs when operating system is Windows and Scala version is 2.13
  }
  test("normal test") {
    // Always runs like a normal test.
  }
}
```

Changing from `options.tags` to `test.tags` solves one of the errors (please confirm this fix is correct).

The `if (isIgnored) test.withBody(() => Ignore)` line is still erroring out with this message:

[error] /Users/powers/Documents/code/my_apps/munit-example/src/test/scala/com/github/mrpowers/munit/example/RichFiltersSpec.scala:16:40: type mismatch;
[error]  found   : munit.Tag
[error]  required: MySuite.this.TestValue
[error]     (which expands to)  scala.concurrent.Future[Any]
[error]     if (isIgnored) test.withBody(() => Ignore)
[error]                                        ^
[error] one error found
[error] (Test / compileIncremental) Compilation failed

Thanks for building this awesome library!

**Comment by olafurpg** [comment]
Thank you for reporting! The example from the blog post has stopped working since the v0.5 release when all internals became async. I opened #63 fixing the code example from the blog post and improved the UX around how the `Ignore` tag is handled. The filtering example with the next release is like this
```scala
  override def munitNewTest(test: Test): Test = {
    val isIgnored =
      test.tags(Windows213) && !(
        Properties.isWin &&
        Properties.versionNumberString.startsWith("2.13")
      )
    if (isIgnored) test.tag(Ignore)
    else test
  }
```

**Comment by MrPowers** [comment]
@olafurpg - thanks for the response!

I tried out your code snippet and it's not working as expected.  [Here is the code I am running](https://github.com/MrPowers/munit-example/blob/master/src/test/scala/com/github/mrpowers/munit/example/RichFiltersSpec.scala).

When I run `testOnly com.github.mrpowers.munit.example.MySuite`, I expect the `windows-213` test to get skipped because I am using Scala 2.12 and macOS, but it looks like it is still getting run.

<img width="1277" alt="Screen Shot 2020-03-08 at 11 53 06 AM" src="https://user-images.githubusercontent.com/2722395/76167283-74431080-6133-11ea-81c9-b3ef8948def0.png">

`Properties.isWin` and `Properties.versionNumberString.startsWith("2.13")` are both false.

Is `test.tag(Ignore)` working or am I missing something?  Sorry in advance if I am doing something silly here!

**Comment by olafurpg** [comment]
It's expected the code snippet doesn't work with the current version of Metals but it will work with the next version after the fixes in #63 are released

**Comment by olafurpg** [comment]
I'm preparing another change I would like to include in the next release as well

**Comment by MrPowers** [comment]
@olafurpg - awesome, thanks for clarifying (I should have seen that in your original message).

This rich filtering options is so awesome - keep up the great work!

**Comment by olafurpg** [comment]
@MrPowers I opened #64 to (hopefully) simplify how to customize filtering and evaluation of tests. The code example from the blog post would become this instead
```scala
import scala.util.Properties
import munit._
object Windows213 extends Tag("Windows213")
class MySuite extends FunSuite {
  override def munitTestTransforms = super.munitTestTransforms ++ List(
    new TestTransform("Windows213", { test =>
      val isIgnored =
        test.tags(Windows213) && !(
          Properties.isWin &&
            Properties.versionNumberString.startsWith("2.13")
        )
      if (isIgnored) test.tag(Ignore)
      else test
    })
  )

  test("windows-213".tag(Windows213)) {
    // Only runs when operating system is Windows and Scala version is 2.13
  }
  test("normal test") {
    // Always runs like a normal test.
  }
}
```

A `TestTransform` is a `Test => Test` function that can for example add tags like `Ignore`.  There is also `SuiteTransform` which is a `List[Test] => List[Test]` to filter tests from a suite.

I'm curious to hear your thoughts if this new API makes sense?

**Comment by MrPowers** [comment]
@olafurpg - I updated [my blog post](https://mungingdata.com/scala/testing-munit/) to reflect the latest API.

I will email you so we can brainstorm how to market this feature!  This functionality will be really useful for the Spark community!
