### ISSUE TITLE
Release 1.0.0-M8

### ISSUE THREAD

**Issue by jvican** [scalameta/munit#654]
There has been quite a lot of progress in the repo! While looking at the docs, I saw a feature I wanted to use: Customize value printers https://scalameta.org/munit/docs/tests.html#customize-value-printers

Can we cut a new milestone release so we can depend on it? It looks like it hasn't been released yet.

**Comment by SethTisue** [comment]
related: https://github.com/scalameta/munit/issues/647

**Comment by valencik** [comment]
1.0.0-M8 has now been released https://github.com/scalameta/munit/releases/tag/v1.0.0-M8

It includes the Printer customization improvements from https://github.com/scalameta/munit/pull/640
