### ISSUE TITLE
Update build to support Dotty 0.23.0-RC1

### ISSUE THREAD

**Issue by gzoller** [scalameta/munit#67]
This is a tracking issue.  Dotty 0.23.0-RC1 has been tagged and is due to drop imminently.  There are some minor code changes required to support the move from 0.22 to 0.23.  I have a PR ready to submit as soon as it drops.  This issue is to track and raise awareness for this change, and can be closed if/when the PR is merged.

**Comment by gzoller** [comment]
PR submitted and CI tests passed.

**Comment by gzoller** [comment]
I also just noticed that there are not Dotty builds released into maven central.  Is that true?  It'd be super-nice if these were published.  Right now munit is really the only workable test framework for Dotty, so it'd be very handy for those of us developing Dotty-based projects to have munit as a downloadable dependency.

**Comment by gzoller** [comment]
Actually--you're right.  I re-tried my build with "using" back in and it worked.   Pushing update in a few minutes.

**Comment by olafurpg** [comment]
Fixed in #69
