### ISSUE TITLE
Broken Scala Native tests on v1.0.0-M9

### ISSUE THREAD

**Issue by valencik** [scalameta/munit#695]
The latest milestone release ([v1.0.0-M9](https://github.com/scalameta/munit/releases/tag/v1.0.0-M9)) appears to break tests on Scala Native.
The likely culprit is some complication with https://github.com/scalameta/munit/pull/693 interacting with cats-effect.

Related links:

- [munit-cats-effect failing build on M9](https://github.com/typelevel/munit-cats-effect/actions/runs/6188155190/job/16799550327)

- https://github.com/scala-native/scala-native/issues/3464

**Edit**: If downstream users see an error like:

```
[error] /usr/bin/ld: /home/runner/work/lucille/lucille/core/.native/target/scala-3.3.1/native-test/native-code-nativelib_native0.4_3-0.4.15-1/scala-native/gc/immix/Marker.c.o: in function `Object_IsWeakReference':
[error] Marker.c:(.text+0x88): undefined reference to `__weak_ref_ids_min'
[error] /usr/bin/ld: Marker.c:(.text+0xa2): undefined reference to `__weak_ref_ids_max'
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is actually caused by not being on the latest [Scala Native 0.4.15](https://github.com/scala-native/scala-native/releases/tag/v0.4.15)

**Comment by armanbilge** [comment]
More details in this CE issue.

- https://github.com/typelevel/cats-effect/issues/3827

I'm operating under the assumption that this is a CE bug, but I'm not sure yet.

**Comment by armanbilge** [comment]
I was able to reproduce without CE.

```scala
//> using dep org.scalameta::munit::1.0.0-M9
//> using nativeVersion 0.4.15

import scala.concurrent.duration.*
import scala.concurrent.*

class MySuite extends munit.FunSuite:
  override implicit def munitExecutionContext = ExecutionContext.global

  test("boo"):
    val p = Promise[Unit]()
    ExecutionContext.global.execute { () =>
      Thread.sleep(1000)
      p.success(())
    }
    p.future
```

**Comment by valencik** [comment]
One tiny step further, we can drop the `Thread.sleep()` and still get the failure on native.
Note that this now also runs on Scala JS and passes there.

```scala
//> using dep org.scalameta::munit::1.0.0-M9
//> using nativeVersion 0.4.15

import scala.concurrent.duration.*
import scala.concurrent.*

class MySuite extends munit.FunSuite:
  override implicit def munitExecutionContext = ExecutionContext.global

  test("boo"):
    val p = Promise[Unit]()
    ExecutionContext.global.execute { () => p.success(()) }
    p.future
```

`scala-cli test --native iss695.scala`

```
MySuite:
  + boo 0.00s
Test runner interrupted by fatal signal 9
Error: scala.scalanative.testinterface.common.RPCCore$ClosedException: scala.scalanative.testinterface.NativeRunnerRPC$RunTerminatedException
```

`scala-cli test --js iss695.scala`

```
MySuite:
  + boo 0.00s
```
