### ISSUE TITLE
Drop Support for Scala 2.11

### ISSUE THREAD

**Issue by valencik** [scalameta/munit#707]
Our Scala.js dependency bumps are failing because Scala.js dropped support for Scala 2.11 support in 1.13.0
https://github.com/scalameta/munit/pull/665#issuecomment-1656727578

We could perhaps stop publishing a Scala.js build just on 2.11, or we could drop 2.11 support altogether.

Unless there are strong reasons to continue supporting 2.11, I think we should drop it.

**Comment by SethTisue** [comment]
doooooooo iiiiiiiit

**Comment by tgodzik** [comment]
People can always freeze their version for 2.11.x if needed. Besides it's highly possible that munit is mostly used for newer projects anyway.
