### ISSUE TITLE
Possibly add native Scala mocking

### ISSUE THREAD

**Issue by MrPowers** [scalameta/munit#75]
It might be nice to add a native Scala mocking solution to MUnit.  Your [scalameta](https://github.com/scalameta/scalameta) expertise might help ;)

I asked about the [future of mocking in Scala](https://www.reddit.com/r/scala/comments/exrsbu/future_of_mocking_in_scala/) and it seems like most folks use [mockito-scala](https://github.com/mockito/mockito-scala).

Looks like mockito-scala [might only work with scalatest and specs2](https://github.com/mockito/mockito-scala/blob/release/1.x/build.sbt#L187) - not sure.

[ScalaMock](https://github.com/paulbutcher/ScalaMock) can only mock traits and no-args classes  .  It looks like they were waiting for [scala.meta to be released](https://github.com/paulbutcher/ScalaMock/issues/33#issuecomment-142340926) and then the project lost steam.

I found it easier to write mocks in other languages:

* Python [has mocking built into unittest](https://docs.python.org/3/library/unittest.mock.html).  unittest is built into Python, so all Python projects have easy access to mocking.
* Ruby's [rspec mocking](https://github.com/rspec/rspec-mocks) is the best mocking syntax / framework I've worked with.  Mocking in RSpec didn't require detailed thought like it does for other frameworks.

Let me know what you think!

**Comment by olafurpg** [comment]
Thank you for reporting! I don’t have any experience with mocking so I’m not familiar with what a library like mockito provides. My understanding is that mocking is helpful in certain kinds of codebases but mocking can often be avoided by using a different design (which might be more idiomatic Scala)

**Comment by MrPowers** [comment]
@olafurpg - Here's a code snippet where mocking would be useful:

```scala
def sendMessageToSlack(text: String): Unit = {
  val slackMessage = new SlackMessage()
  slackMessage.setText(text)
  slackApi.call(slackMessage)
}

def mySillyFunction(): Int = {
  val res = 2 + 2
  sendMessageToSlack("We just computed 2 + 2!!!")
  res
}
```

Think you need mocking to be able to test `sendMessageToSlack` and `mySillyFunction`.  In `mySillyFunction`, we don't actually want to run the `sendMessageToSlack` method.  We just want to make sure that the method would be invoked with the argument `"We just computed 2 + 2!!!"`.

I haven't used mockito-scala yet either.  I will create a sample project and a blog post to discuss the key features.  Will report back on this issue with my findings ;)

**Comment by olafurpg** [comment]
After more consideration I believe mocking is outside the scope of this library. I'm open to add integration modules with existing mocking libraries if there's demonstrable value (like with munit-scalacheck) but I don't think any remotely interesting mocking library will quickly outgrow MUnit in complexity to merit a separate repo.

**Comment by MrPowers** [comment]
Sounds good, thanks for considering this.

**Comment by FloWi** [comment]
> My understanding is that mocking is helpful in certain kinds of codebases but mocking can often be avoided by using a different design (which might be more idiomatic Scala)

Hi @olafurpg! Would you mind elaborating on that? In my scenario I have a complex trait generated by smithy4s and I would like to mock only a handful of functions for a certain test. I'd be interested in knowing how to do that the idiomatic scala way.
