### ISSUE TITLE
Extract munit-scalacheck to a different repo/sbt project

### ISSUE THREAD

**Issue by JD557** [scalameta/munit#758]
From the MUnit ["Getting Started"](https://scalameta.org/munit/docs/getting-started.html) page:

> MUnit is a Scala testing library with the following goals:
>
> [...]
> **No Scala dependencies:** MUnit has no external Scala dependencies so that it can easily cross-build against a wide range of Scala compiler versions.

This goal is not entirely true, due to the dependency on ScalaCheck. Sure, it's just a submodule, but having it on the same sbt project can still be a nuisance - e.g. it's currently blocking (or at least making extra cumbersome) the upgrade path to Scala Native 0.5.0.

[All other integrations](https://scalameta.org/munit/docs/integrations/external-integrations.html) live on separate repos, so it's also a bit odd to see ScalaCheckget a preferential treatment.

**Comment by tgodzik** [comment]
Turns out this was already problematic since we can't release for 0.5.x without moving scalacheck separately, so I created https://github.com/scalameta/munit-scalacheck
