### ISSUE TITLE
Publish for Scala Native 0.5, please

### ISSUE THREAD

**Issue by SethTisue** [scalameta/munit#760]
this will unblock a bunch of downstream libraries from also publishing for 0.5

**Comment by tgodzik** [comment]
Question, should we:
1. drop 0.4.x and release a new milestone (I intend to address the milestone elephant in the room in the near future)
2. backport 0.5.x to the latest milestone
3. Try cross publishing for 0.4 and 0.5

I can do 2. manually now to unblock downstream projects, but is it enough to do 1 later on?

**Comment by valencik** [comment]
I think we're blocked by https://github.com/scala/scala3/pull/20171

**Comment by tgodzik** [comment]
> > 3. Try cross publishing for 0.4 and 0.5
> 
> Definitely not this.

Yep, that's what I was hoping not to do :D

I backported munit 1.0.0-M11 for 2.13, 2.12 and 3. 

munit-scalafix requires scalafix to be released for 0.5.0

I will bump native version in the repo once that is out and next releases would be for 0.5 then.

**Comment by mpilquist** [comment]
scalacheck 1.18.0 has been published for native 0.5.

**Comment by tgodzik** [comment]
Thanks!
