### ISSUE TITLE
Skipped tests printed v1.0.0

### ISSUE THREAD

**Issue by aherlihy** [scalameta/munit#791]
Hi, I was excited to see [skipped tests would not be printed](https://github.com/scalameta/munit/pull/779) since I find it makes parsing test output difficult when munit will print hundreds of non-running tests in green, interweaved with the results of tests that were actually run. However when I rebuilt with v1.0.0 I noticed these tests are still printed, even if they are not run, when using `testOnly -- <regex>`. I'm not sure if this is a bug, or if it's intentional, then I'd like to make a feature request to enable turning off printing tests that didn't run in the identical way as tests that ran and passed. Thanks!

**Comment by tgodzik** [comment]
I don't think we merged it into v1.0.0 actually. You could try out a snapshot version like `1.0.0+24-ee555b1d-SNAPSHOT` available in the sonatype/snapshots repository.

**Comment by mzuehlke** [comment]
https://github.com/scalameta/munit/compare/v1.0.0...main
this shows it got merged after the release 👍

**Comment by aherlihy** [comment]
Ah I see, thanks for the clarification!
