### ISSUE TITLE
Location macro is non-hermetic

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/munit#822]
## Steps

1. Write any tests, and compile the code.
2. Now take the same code, and move it to another directory.

The bytecode contains the full path of the source code due to Location macro.

## Problem

For the purpose of remote caching and reproducible build, using the absolute path doesn't work well.

**Comment by mzuehlke** [comment]
There already exist an old but very similar issue: #382

**Comment by eed3si9n** [comment]
ok. I'll close this as a duplicate.
