### ISSUE TITLE
Extract the Printers into munit-diff

### ISSUE THREAD

**Issue by msosnicki** [scalameta/munit#826]
In the #756  munit-diff was extracted, so that it can be used outside of munit context, as it is a very useful micro library.

The diffing mechanism is based on `class Diff(val obtained: String, val expected: String)`, where a string representation of a datatype is expected. It is optimized for the [Printers](https://github.com/scalameta/munit/blob/b02ef31983df653014ab22244f1815cb9d066fb5/munit/shared/src/main/scala/munit/internal/console/Printers.scala#L23), which are currently in `munit` module (for `toString` it doesn't work as nicely, in munit it is merely a fallback mechanism if Printers do not reveal any difference).

I can work on extracting it into `munit-diff`, but wanted to ask for green light here, maybe there are some gotchas that I missed and it was left out on purpose.

**Comment by tgodzik** [comment]
I don't remember any issues, but maybe @majk-p does?

**Comment by majk-p** [comment]
Cant tell for sure, but likely it was due to `Printers` dependency on `munit.Clue`, which we didn't want to include in `munit.diff`.

**Comment by msosnicki** [comment]
I'm closing this issue, turns out there is [an ongoing effort](https://github.com/typelevel/weaver-test/pull/64) to have the pretty diffing baked into weaver as part as [ongoing migration to typelevel](https://github.com/typelevel/weaver-test/issues/1).
