### ISSUE TITLE
Is there a way to share tests between suites without using inheritance?

### ISSUE THREAD

**Issue by AugustNagro** [scalameta/munit#854]
For example something like

```scala
class SharedTests:
  def testInsert(dbType)(using munit.Location): Unit =
    test("test insert"):
      // use dbType to run insert

class PgTests extends FunSuite:
  testInsert(PgDbType)

class MySqlTests extends FunSuite:
  testInsert(MySqlDbType)
```

**Comment by tgodzik** [comment]
Does it work for you? I think it might, but doesn't looks like it would be easiest to debug if someone was not familiar with the projects.

**Comment by AugustNagro** [comment]
No, unfortunately running PgTests won't execute the shared test.

Not a big deal or high priority issue, since using inheritance works fine.

**Comment by AugustNagro** [comment]
My bad; it definitely is possible if you pass the FunSuite Instance.

But like you said, it simply makes more sense to have utility method as described in https://scalameta.org/munit/docs/tests.html#declare-tests-inside-a-helper-function
