### ISSUE TITLE
Please publish Dotty versions to repo

### ISSUE THREAD

**Issue by gzoller** [scalameta/munit#92]
It would be great if Dotty versions of munit could be published to the maven repo.

Currently munit is one of the only testing frameworks for Dotty, so it's important in that community to have a current version.  I've been maintaining and publishing a Dotty build in my repo, but an official release would be super.  I'm currently built off of Dotty 0.24-RC1 against JDK11.

**Comment by olafurpg** [comment]
Thank you for reporting! We are able to cross-build against multiple Dotty versions if that helps. I'm open to merge a PR that adds cross-building for 0.23/0.24. Each merged commit is published immediately as a SNAPSHOT, and we can trigger a stable release if you need a non-SNAPSHOT (although I would ideally like to limit those to no more than one stable release per week)

**Comment by gzoller** [comment]
Happy to PR for 0.23/0.24 cross building.  0.24 is the "standard" now that it's in RC, but there are still folks out there using 0.23.  Where are the snapshots published?  I may be looking in the wrong place and not finding them.  I'm thinking a non-SNAPSHOT release (for Dotty anyway) would be on each major version: 0.23, 0.24, 0.25, and between RCs: -RC1, -RC2.  This frequency is a lot less than once per week and I think you will likely release munit itself more frequently in many cases.

**Comment by olafurpg** [comment]
You can see the snapshot releases here https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/munit_0.23/

We can cut a stable MUnit release for every new 0.x release of Dotty 👍

**Comment by gzoller** [comment]
That's great news.  Thank you.  I'll close this issue then.  I got ahead of myself with 0.24.  I see it's not yet RC1.
