### ISSUE TITLE
Feature Req: Describe section

### ISSUE THREAD

**Issue by gzoller** [scalameta/munit#93]
I know the main philosophy of munit is to keep it lean and simple, so I understand if this feature is not part of that picture--but I'll ask anyway.

There are so many great highlighting features in munit I don't miss my old standby test framework, scalatest a lot.  One feature scalatest did have that was nice to have was a describe{} section that allowed tests in a file to be sectioned and intended.

For example:
```scala
describe(
    "---------------------------\n:  Scala Primitive Tests  :\n---------------------------"
  ) {
      describe("+++ Positive Tests +++") {
           // several tests here
      }
      describe("+++ Positive Tests +++") {
           // several tests here
      }
}
```
This would produce a nice sectioned display:
```
---------------------------
:  Scala Primitive Tests  :
---------------------------
+++ Positive Tests +++
   -- test output
   -- test output
+++ Positive Tests +++
   -- test output
   -- test output
```

This feature is a nice way to section and format groups of tests.  Describe is only an output/formatting thing--it doesn't "do" anything in terms of the tests themselves.

**Comment by olafurpg** [comment]
Thank you for reporting! I am concerned this is a slippery slope to take. Can you elaborate on the difference between `describe(..)` and `println(..)` with some ANSI colors? Is the following a valid workaround?

```scala
import munit.internal.consol
def describe(message: String)(thunk: => Unit): Unit = {
  println(Console.GREEN + messsage + Console.RESET)
  thunk
}
```
The only difference from what I can see is that the "test output" lines will not be indented

**Comment by gzoller** [comment]
This is very close.  I can live w/o the indent, and I do understand the slippery slope.

When I do this, with this decribe() method:
```scala
describe("---A---") {
   test("Foo") {...}
   test("Bar") {...}
describe("---B---") {
   test("Blather") {...}
   test("Baz") {...}
}
```
I get this output
```
---A---
---B---
  + Foo
  + Bar
  + Blather
  + Baz
```
I was hoping for:
```
---A---
  + Foo
  + Bar
---B---
  + Blather
  + Baz
```
Can this be done with the facilities already in munit?

**Comment by gzoller** [comment]
Did some experiments implementing munit.Printer and munit.Printable, mainly just to see if anything passed through there.  In my tests, nothing passed thru print() (nothing was output), so maybe I haven't wired it up correctly?  Don't know if this is the right direction, but it is what I tried next.
```scala
class Collections extends munit.FunSuite with munit.Printer {
  def print(value: Any, out: StringBuilder, indent: Int): Boolean = {
    println("HERE: "+value)
    false
  }
  override def height: Int = 100
  override def isMultiline(string: String): Boolean =
    string.contains('\n')

 ...
}
```

**Comment by gzoller** [comment]
This works:
```scala
class Collections extends munit.FunSuite {

  inline def describe(message: String): Unit = println(Console.MAGENTA + message + Console.RESET)

  test("Foo") {
    describe("---- A ----")
   ...
  }
  test("Bar") {
   ...
  }
  test("Blather") {
    describe("---- B ----")
   ...
  }
  test("Baz") {
   ...
  }
```
Not super-elegant, but it does work as I need it to, and requires no surgery to munit.
Open to better options, if any, but I'm good with this.  Closing issue.
