### ISSUE TITLE
Support specifying test options on Dotty without enabling implicit conversions

### ISSUE THREAD

**Issue by mpilquist** [scalameta/munit#96]
build.sbt:
```scala
scalaVersion := "0.23.0-RC1"
libraryDependencies += "org.scalameta" %% "munit" % "0.7.1"
testFrameworks += new TestFramework("munit.Framework")
```

Source:
```scala
package foo

import munit.FunSuite

class Foo extends FunSuite {
  test("foo".ignore) {
    assert(true)
  }
}
```

Result of compiling:
```
[info] Compiling 1 Scala source to /Users/mpilquist/Development/oss/munit-example/target/scala-0.23/classes ...
[warn] -- Feature Warning: /Users/mpilquist/Development/oss/munit-example/src/main/scala/Test.scala:6:7
[warn] 6 |  test("foo".ignore) {
[warn]   |       ^^^^^
[warn]   |Use of implicit conversion method testOptionsFromString in trait TestOptionsConversions should be enabled
[warn]   |by adding the import clause 'import scala.language.implicitConversions'
[warn]   |or by setting the compiler option -language:implicitConversions.
[warn]   |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]   |why the feature should be explicitly enabled.
[warn] one warning found
```

If we change `testOptionsFromString` from an implicit def to an implicit `Conversion[String, TestOptions]`, along with a shim definition of `type Conversion[-A, +B] = A => B` on Scala 2, we can avoid this warning.

**Comment by olafurpg** [comment]
Thank you for reporting! This is a good suggestion, normal usage of MUnit should not trigger compiler warnings when using default compiler flags.

> If we change testOptionsFromString from an implicit def to an implicit Conversion[String, TestOptions], along with a shim definition of type Conversion[-A, +B] = A => B on Scala 2, we can avoid this warning.

I did not know about this trick. It sounds like an escape hatch that may get removed in the future, have you checked with the Dotty team to confirm that this workaround will continue to work in Scala 3?

**Comment by olafurpg** [comment]
Alternatively, could we add extension methods in Scala 3 and keep the implicit conversion in Scala 2? 🤔

**Comment by mpilquist** [comment]
Hm, I'm wrong about `Conversion`:

```scala
scala> {
     | case class Foo(x: String)
     | object Foo {
     |   implicit def stringToFoo: Conversion[String, Foo] = Foo(_)
     | }
     | def bar(f: Foo) = f
     | bar("hi")
     | }
7 |bar("hi")
  |    ^^^^
  |Use of implicit conversion trait Function1 in package scala should be enabled
  |by adding the import clause 'import scala.language.implicitConversions'
  |or by setting the compiler option -language:implicitConversions.
  |See the Scala docs for value scala.language.implicitConversions for a discussion
  |why the feature should be explicitly enabled.
// defined case class Foo
// defined object Foo
def bar(f: Foo): Foo
val res1: Foo = Foo(hi)

scala> {
     | case class Foo(x: String)
     | object Foo {
     |   implicit def stringToFoo: Conversion[String, Foo] = Foo(_)
     | }
     | def bar(f: Foo) = f
     | bar("hi")
     | }
7 |bar("hi")
  |    ^^^^
  |Use of implicit conversion trait Function1 in package scala should be enabled
  |by adding the import clause 'import scala.language.implicitConversions'
  |or by setting the compiler option -language:implicitConversions.
  |See the Scala docs for value scala.language.implicitConversions for a discussion
  |why the feature should be explicitly enabled.
// defined case class Foo
// defined object Foo
def bar(f: Foo): Foo
val res2: Foo = Foo(hi)
```

**Comment by gabro** [comment]
@olafurpg AFAIK that's the way Dotty "normalized" implicit conversions, i.e. by applying them only when an implicit instance of `Conversion` is in scope. This is done to prevent warts such as picking up unwanted implicits (such as an implicit Map or Set, which extend Function1 and were therefore used as conversion in Scala 2).

I think the old-style conversions are supported for compatibility reasons, but going forward `Conversion` will be required for the pattern to work.

I haven't seed discussions about putting the feature behind a flag, so I think it's reasonable to expect that it will keep working in Scala 3.

Sources:
- documentation on the dotty website: https://dotty.epfl.ch/docs/reference/contextual/conversions.html (it also references the magnet pattern, which is what we're using here)
- more details about the change: https://dotty.epfl.ch/docs/reference/changed-features/implicit-conversions-spec.html

**Comment by gabro** [comment]
@mpilquist that's in Scala 2, right?

I suppose

```scala
given Conversion[String, Foo] = new Foo(_)
```

does not rise any warning in Dotty

**Comment by mpilquist** [comment]
That's 0.23.0-RC1, though good point about using given. Note the warning has moved from declaration site to use site in Dotty.

```scala
scala> {
     | case class Foo(x: String)
     | object Foo {
     |   given stringToFoo as Conversion[String, Foo] = Foo(_)
     | }
     | def bar(f: Foo) = f
     | bar("hi")
     | }
7 |bar("hi")
  |    ^^^^
  |Use of implicit conversion trait Function1 in package scala should be enabled
  |by adding the import clause 'import scala.language.implicitConversions'
  |or by setting the compiler option -language:implicitConversions.
  |See the Scala docs for value scala.language.implicitConversions for a discussion
  |why the feature should be explicitly enabled.
// defined case class Foo
// defined object Foo
def bar(f: Foo): Foo
val res3: Foo = Foo(hi)
```

**Comment by gabro** [comment]
Ok, it seems I was wrong. 

```
import scala.language.implicitConversion
```

is still required even with the new `Conversion` trait

**Comment by olafurpg** [comment]
Do you know if there are plans to remove support for implicit conversions in Dotty? If not, then I'm inclined to close this as wontfix and update the documentation to require `-language:implicitConversions` or `import scala.language.implicitConversions`. If somebody want's to take on this ticket then I think the best solution is to use extension methods in Scala 3 and keep the implicit conversion in Scala 2.

**Comment by gabro** [comment]
👍 for a wontfix
