### ISSUE TITLE
Using the test reporter without using MUnit as test framework

### ISSUE THREAD

**Issue by afiore** [scalameta/munit#98]
Hi there,

I am trying to use the MUnit sbt plugin as described [here](https://scalameta.org/munit/docs/reports.html#__docusaurus) in order to generate an HTML test report for my project. I am boldly assuming that I can do so even if I am not using MUnit as the project test framework (my project uses Scalatest instead, which should still generate JUnit compliant XML results). 

## Sbt changes

I have defined a subproject that depends on another project/module in my build:

```
lazy val `lenses-domain-core-docs` =
  project
    .in(file("project-x-docs"))
    .dependsOn(`project-x`)
    .settings(
      mdocVariables := Map(
        "VERSION" -> version.value,
      ),
      mdocIn := file("project-x-docs/docs"),
    )
    .enablePlugins(MdocPlugin, MUnitReportPlugin)
``` 

When I run `sbt 'project-x-docs/mdoc'` I can see Mdoc working as expected and compiling scala snippets in my markdown files. However, the HTML report generation fails with a warning:

```
warning: Unable to generate MUnit HTML test report.
```
Is there a way to troubleshoot this error, perhaps by making the plugin more verbose?

## Google Cloud Storage setup

Notice that, I have exported the `GOOGLE_APPLICATION_CREDENTIALS_JSON` and `GOOGLE_APPLICATION_CREDENTIALS` env variable pointing to a service account that has admin access to Google storage on my Gcloud. However, I could not create a bucket named `munit-test-reports` as I believe these have to be unique across accounts.

![image](https://user-images.githubusercontent.com/63361/78390594-ba797b80-75dc-11ea-9ca6-8e11965a78ca.png)

Finally, this is the content of the property file generated by MUnit in `resource_managed`:

```
❮ cat ./project-x-docs/target/scala-2.12/resource_managed/main/munit.properties
#MUnit properties
#Fri Apr 03 17:59:17 BST 2020
munitBucketName=munit-test-reports
```

**Comment by olafurpg** [comment]
@afiore any update on this? The bucket name is configurable 

```scala
munitBucket := Some("my-custom-bucket-name")
```

https://github.com/scalameta/munit/blob/f61429f66f8fd81ee71e6c10dc2fe212073b5b07/munit-sbt/src/main/scala/munit/sbtmunit/MUnitPlugin.scala#L16

**Comment by olafurpg** [comment]
Feel free to reopen to continue the discussion.
